### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by FinnBaltazar1111** [kleo/fusee-alpestre#4]
I flash one of the prebuilt release files to a microSD card using the RPI imager. I plug in my Switch (in RCM) to a USB hub and into my Pi Zero 2 W. I put in the microSD card and power on the Pi. The Pi's power light stays off and nothing happens to the switch.

**Comment by 5543Mj** [comment]
Found the problem, all of the data is in an in file it should not be.
In order to fix... 
1. Mount the .img file to your computer to edit the files.
2. Open the file labeled "boot"
3. Take all of the files inside the "boot" folder and move them out onto the root of the .img file

**Comment by FinnBaltazar1111** [comment]
> Found the problem, all of the data is in an in file it should not be. In order to fix...
> 
> 1. Mount the .img file to your computer to edit the files.
> 2. Open the file labeled "boot"
> 3. Take all of the files inside the "boot" folder and move them out onto the root of the .img file
> 4. Flash the sd card

Thanks! I'll try this later today, and I'll close this issue if it works.

**Comment by FinnBaltazar1111** [comment]
This works great! Thanks for your help.
